[#day2-mgmt-cluster]
= Management Cluster
:experimental:

ifdef::env-github[]
:imagesdir: ../images/
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]
:toc: preamble

This section covers how to perform the various `Day 2` operations related to upgrading your `management` cluster from one Edge platform version to another.

The `Day 2` operations are automated by the <<components-upgrade-controller, Upgrade Controller>> and include:

* <<components-slmicro, SL Micro>> OS upgrade

* <<components-rke2, RKE2>>/<<components-k3s, K3s>> upgrade

* SUSE additional components (Rancher, Neuvector, etc.) upgrade

== Prerequisites

Before upgrading your `management` cluster, the following prerequisites must be met:

. `SCC registered nodes` - ensure your cluster nodes' OS are registered with a subscription key that supports the OS version specified in the Edge <<release-notes,release>> you intend to upgrade to.

. `Upgrade Controller` - make sure that the `Upgrade Controller` has been deployed on your `management` cluster. For installation steps, refer to <<components-upgrade-controller-installation, Installing the Upgrade Controller>>.

== Upgrade

. Determine the Edge <<release-notes,release>> version that you wish to upgrade your `management` cluster to.

. In the `management` cluster, deploy an `UpgradePlan` that specifies the desired `release version`. The `UpgradePlan` must be deployed in the namespace of the `Upgrade Controller`.
+
[,bash]
----
kubectl apply -n <upgrade_controller_namespace> -f - <<EOF
apiVersion: lifecycle.suse.com/v1alpha1
kind: UpgradePlan
metadata:
  name: upgrade-plan-mgmt-3-1-X
spec:
  # Version retrieved from release notes
  releaseVersion: 3.1.X
EOF
----
+
[NOTE]
====
There may be use-cases where you would want to make additional configurations over the `UpgradePlan`. For all possible configurations, refer to the <<components-upgrade-controller-extensions-upgrade-plan, UpgradePlan>> section.
====

. Replace the original chart manifest file:
+
[source,bash]
----
cp <chart_name>.yaml /var/lib/rancher/rke2/server/manifests/
----

The above commands will trigger an upgrade of the helm chart. The upgrade will be handled by the https://github.com/k3s-io/helm-controller#helm-controller[helm-controller].

To track the helm chart upgrade you need to view the logs of the pod that the `helm-controller` creates for the chart upgrade. Refer to the <<day2-mgmt-cluster-eib-helm-chart-upgrade-examples, Examples>> section for more information.

[#day2-mgmt-cluster-eib-helm-chart-upgrade-examples]
==== Examples

[NOTE]
====
The examples in this section assume that you have already located and connected to your `initializer` node.
====

This section offer examples on how to upgrade a:

* <<day2-mgmt-cluster-eib-helm-chart-upgrade-examples-rancher, Rancher>> helm chart

* <<day2-mgmt-cluster-eib-helm-chart-upgrade-examples-metal3, Metal^3^>> helm chart

[#day2-mgmt-cluster-eib-helm-chart-upgrade-examples-rancher]
===== Rancher upgrade

[NOTE]
====
To ensure disaster recovery, we advise to do a Rancher backup. For information on how to do this, check link:https://ranchermanager.docs.rancher.com/how-to-guides/new-user-guides/backup-restore-and-disaster-recovery/back-up-rancher[here].
====

This example shows how to upgrade Rancher to the `2.8.8` version.

. Add the `Rancher Prime` Helm repository:
+
[source,bash]
----
helm repo add rancher-prime https://charts.rancher.com/server-charts/prime
----

. Pull the latest `Rancher Prime` helm chart version:
+
[source,bash]
----
helm pull rancher-prime/rancher --version=2.8.8
----

. Encode `.tgz` archive so that it can be passed to a `HelmChart` CR config:
+
[source,bash]
----
base64 -w 0 rancher-2.8.8.tgz  > rancher-2.8.8-encoded.txt
----

. Make a copy of the `rancher.yaml` file that we will edit:
+
[source, bash]
----
cp /var/lib/rancher/rke2/server/manifests/rancher.yaml ./rancher.yaml
----

. Change the `chartContent` and `version` configurations of the `rancher.yaml` file:
+
[source,bash]
----
sed -i -e "s|chartContent:.*|chartContent: $(<rancher-2.8.8-encoded.txt)|" -e "s|version:.*|version: 2.8.8|" rancher.yaml
----
+
[NOTE]
====
For more information on the actual `upgrade process`, refer to <<components-upgrade-controller-how, How does the Upgrade Controller work?>>.

For information on how to track the `upgrade process`, refer to <<components-upgrade-controller-how-track, Tracking the upgrade process>>.
====

. Replace the original `rancher.yaml` file:
+
[source,bash]
----
cp rancher.yaml /var/lib/rancher/rke2/server/manifests/
----

To verify the update:

. List pods in `default` namespace: 
+
[source,bash]
----
kubectl get pods -n default

# Example output
NAME                              READY   STATUS      RESTARTS   AGE
helm-install-cert-manager-7v7nm   0/1     Completed   0          88m
helm-install-rancher-p99k5        0/1     Completed   0          3m21s
----

. Look at the logs of the `helm-install-rancher-*` pod:
+
[source,bash]
----
kubectl logs <helm_install_rancher_pod> -n default

# Example
kubectl logs helm-install-rancher-p99k5 -n default
----

. Verify `Rancher` pods are running:
+
[source,bash]
----
kubectl get pods -n cattle-system

# Example output
NAME                               READY   STATUS      RESTARTS   AGE
helm-operation-mccvd               0/2     Completed   0          3m52s
helm-operation-np8kn               0/2     Completed   0          106s
helm-operation-q8lf7               0/2     Completed   0          2m53s
rancher-648d4fbc6c-qxfpj           1/1     Running     0          5m27s
rancher-648d4fbc6c-trdnf           1/1     Running     0          9m57s
rancher-648d4fbc6c-wvhbf           1/1     Running     0          9m57s
rancher-webhook-649dcc48b4-zqjs7   1/1     Running     0          100s
----

. Verify `Rancher` version upgrade:
+
[source,bash]
----
kubectl get settings.management.cattle.io server-version

# Example output
NAME             VALUE
server-version   v2.8.8
----

[#day2-mgmt-cluster-eib-helm-chart-upgrade-examples-metal3]
===== Metal^3^ upgrade

This example shows how to upgrade Metal^3^ to the `0.7.4` version.

. Pull the latest `Metal^3^` helm chart version:
+
[source,bash]
----
helm pull oci://registry.suse.com/edge/metal3-chart --version 0.7.4
----

. Encode `.tgz` archive so that it can be passed to a `HelmChart` CR config:
+
[source,bash]
----
base64 -w 0 metal3-chart-0.7.4.tgz  > metal3-chart-0.7.4-encoded.txt
----

. Make a copy of the `Metal^3^` manifest file that we will edit:
+
[source, bash]
----
cp /var/lib/rancher/rke2/server/manifests/metal3.yaml ./metal3.yaml
----

. Change the `chartContent` and `version` configurations of the `Metal^3^` manifest file:
+
[source,bash]
----
sed -i -e "s|chartContent:.*|chartContent: $(<metal3-chart-0.7.4-encoded.txt)|" -e "s|version:.*|version: 0.7.4|" metal3.yaml
----
+
[NOTE]
====
If you need to do any additional upgrade changes to the chart (e.g. adding *new* custom chart values), you need to manually edit the `metal3.yaml` file.
====

. Replace the original `Metal^3^` manifest file:
+
[source,bash]
----
cp metal3.yaml /var/lib/rancher/rke2/server/manifests/
----

To verify the update:

. List pods in `default` namespace: 
+
[source,bash]
----
kubectl get pods -n default

# Example output
NAME                              READY   STATUS      RESTARTS   AGE
helm-install-metal3-7p7bl         0/1     Completed   0          27s
----

. Look at the logs of the `helm-install-metal3-*` pod:
+
[source,bash]
----
kubectl logs <helm_install_metal3_pod> -n default

# Example
kubectl logs helm-install-metal3-7p7bl -n default
----

. Verify `Metal^3^` pods are running:
+
[source,bash]
----
kubectl get pods -n metal3-system

# Example output
NAME                                                     READY   STATUS    RESTARTS      AGE
baremetal-operator-controller-manager-785f99c884-9z87p   2/2     Running   2 (25m ago)   36m
metal3-metal3-ironic-96fb66cdd-lkss2                     4/4     Running   0             3m54s
metal3-metal3-mariadb-55fd44b648-q6zhk                   1/1     Running   0             36m
----

. Verify the `HelmChart` resource version is upgraded:
+
[source,bash]
----
kubectl get helmchart metal3 -n default

# Example output
NAME     JOB                   CHART   TARGETNAMESPACE   VERSION   REPO   HELMVERSION   BOOTSTRAP
metal3   helm-install-metal3           metal3-system     0.7.4
----

[#day2-mgmt-cluster-helm-chart-upgrade]
=== Non-EIB deployed helm chart

. Get the values for the currently running helm chart `.yaml` file and make any changes to them *if necessary*:
+
[source,bash]
----
helm get values <chart_name> -n <chart_namespace> -o yaml > <chart_name>-values.yaml
----

. Update the helm chart:
+
[source,bash]
----
# For charts using a chart repository
helm upgrade <chart_name> <chart_repo_name>/<chart_name> \
  --namespace <chart_namespace> \
  -f <chart_name>-values.yaml \
  --version=X.Y.Z

# For OCI based charts
helm upgrade <chart_name> oci://<oci_registry_url>/<chart_name> \
  --namespace <chart_namespace> \
  -f <chart_name>-values.yaml \
  --version=X.Y.Z
----

. Verify the chart upgrade. Depending on the chart you may need to verify different resources. For examples of chart upgrades, see the <<day2-mgmt-cluster-helm-chart-upgrade-examples, Examples>> section.

[#day2-mgmt-cluster-helm-chart-upgrade-examples]
==== Examples

This section offer examples on how to upgrade a:

* <<day2-mgmt-cluster-helm-chart-upgrade-examples-rancher, Rancher>> helm chart

* <<day2-mgmt-cluster-helm-chart-upgrade-examples-metal3, Metal^3^>> helm chart

[#day2-mgmt-cluster-helm-chart-upgrade-examples-rancher]
===== Rancher

[NOTE]
====
To ensure disaster recovery, we advise to do a Rancher backup. For information on how to do this, check link:https://ranchermanager.docs.rancher.com/how-to-guides/new-user-guides/backup-restore-and-disaster-recovery/back-up-rancher[here].
====

This example shows how to upgrade Rancher to the `2.8.8` version.

. Get the values for the current Rancher release and print them to a `rancher-values.yaml` file:
+
[source,bash]
----
helm get values rancher -n cattle-system -o yaml > rancher-values.yaml
----

. Update the helm chart:
+
[source,bash]
----
helm upgrade rancher rancher-prime/rancher \
  --namespace cattle-system \
  -f rancher-values.yaml \
  --version=2.8.8
----

. Verify `Rancher` version upgrade:
+
[source,bash]
----
kubectl get settings.management.cattle.io server-version

# Example output
NAME             VALUE
server-version   v2.8.8
----

_For additional information on the Rancher helm chart upgrade, check link:https://ranchermanager.docs.rancher.com/getting-started/installation-and-upgrade/install-upgrade-on-a-kubernetes-cluster/upgrades[here]._


[#day2-mgmt-cluster-helm-chart-upgrade-examples-metal3]
===== Metal^3^

This example shows how to upgrade Metal^3^ to the `0.7.4` version.

. Get the values for the current Rancher release and print them to a `rancher-values.yaml` file:
+
[source,bash]
----
helm get values metal3 -n metal3-system -o yaml > metal3-values.yaml
----

. Update the helm chart:
+
[source,bash]
----
helm upgrade metal3 oci://registry.suse.com/edge/3.1/metal3-chart \
  --namespace metal3-system \
  -f metal3-values.yaml \
  --version=0.7.4
----

. Verify `Metal^3^` pods are running:
+
[source,bash]
----
kubectl get pods -n metal3-system

# Example output
NAME                                                     READY   STATUS    RESTARTS   AGE
baremetal-operator-controller-manager-785f99c884-fvsx4   2/2     Running   0          12m
metal3-metal3-ironic-96fb66cdd-j9mgf                     4/4     Running   0          2m41s
metal3-metal3-mariadb-55fd44b648-7fmvk                   1/1     Running   0          12m
----

. Verify `Metal^3^` helm release version change:
+
[source,bash]
----
helm ls -n metal3-system

# Expected output
NAME    NAMESPACE      REVISION  UPDATED                                  STATUS    CHART         APP VERSION
metal3  metal3-system  2         2024-06-17 12:43:06.774802846 +0000 UTC  deployed  metal3-0.7.4  1.16.0
----
